services:
  - type: web
    name: politiekpraat
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /
    buildCommand: ""
    startCommand: "" 