-- Create amerikaanse_verkiezingen table for US presidential elections data
CREATE TABLE IF NOT EXISTS amerikaanse_verkiezingen (
    id INT AUTO_INCREMENT PRIMARY KEY,
    jaar INT NOT NULL UNIQUE,
    winnaar VARCHAR(255) NOT NULL,
    winnaar_partij VARCHAR(100) NOT NULL,
    winnaar_kiesmannen INT NOT NULL,
    verliezer VARCHAR(255) NOT NULL,
    verliezer_partij VARCHAR(100) NOT NULL,
    verliezer_kiesmannen INT NOT NULL,
    winnaar_stemmen_populair INT NOT NULL,
    verliezer_stemmen_populair INT NOT NULL,
    winnaar_percentage_populair DECIMAL(5,2) NOT NULL,
    verliezer_percentage_populair DECIMAL(5,2) NOT NULL,
    totaal_kiesmannen INT NOT NULL DEFAULT 538,
    opkomst_percentage DECIMAL(5,2),
    belangrijkste_themas JSON,
    belangrijke_gebeurtenissen TEXT,
    opvallende_feiten TEXT,
    verkiezingsdata DATE,
    inhuldiging_data DATE,
    bronnen JSON,
    extra_kandidaten JSON,
    beschrijving TEXT,
    winnaar_foto_url VARCHAR(2083),
    verliezer_foto_url VARCHAR(2083),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_jaar (jaar),
    INDEX idx_winnaar_partij (winnaar_partij),
    INDEX idx_verkiezingsdata (verkiezingsdata)
); 
