INSERT IGNORE INTO nederlandse_verkiezingen (
    jaar,
    partij_uitslagen,
    coalitie_partijen,
    coalitie_zetels,
    coalitie_type,
    oppositie_partijen,
    minister_president,
    minister_president_partij,
    kabinet_naam,
    kabinet_type,
    totaal_zetels,
    totaal_stemmen,
    opkomst_percentage,
    kiesdrempel_percentage,
    verkiezingsdata,
    kabinet_start_datum,
    kabinet_eind_datum,
    formatie_duur_dagen,
    verkiezings_aanleiding,
    belangrijkste_themas,
    belangrijke_gebeurtenissen,
    opvallende_feiten,
    nieuwe_partijen,
    verdwenen_partijen,
    grootste_winnaar,
    grootste_winnaar_aantal,
    grootste_verliezer,
    grootste_verliezer_aantal,
    aantal_partijen_tk,
    kiesdrempel_gehaald,
    kiesdrempel_gemist,
    lijsttrekkers,
    tv_debatten,
    verkiezingsuitslag_tijd,
    opkomst_verschil_vorige,
    beschrijving,
    bronnen,
    foto_url
)
VALUES (
    2025,
    '[{"partij":"PVV","zetels":41,"stemmen":2726000,"percentage":26.0},{"partij":"VVD","zetels":28,"stemmen":1843000,"percentage":17.5},{"partij":"GL-PvdA","zetels":22,"stemmen":1442000,"percentage":13.7},{"partij":"NSC","zetels":15,"stemmen":1078000,"percentage":10.2},{"partij":"D66","zetels":12,"stemmen":927000,"percentage":8.8},{"partij":"BBB","zetels":8,"stemmen":616000,"percentage":5.9},{"partij":"SP","zetels":7,"stemmen":521000,"percentage":5.0},{"partij":"CDA","zetels":6,"stemmen":446000,"percentage":4.2},{"partij":"Volt","zetels":4,"stemmen":304000,"percentage":2.9},{"partij":"JA21","zetels":3,"stemmen":237000,"percentage":2.3},{"partij":"DENK","zetels":3,"stemmen":216000,"percentage":2.1},{"partij":"Nederland Vooruit (NV)","zetels":1,"stemmen":168000,"percentage":1.6}]',
    '["PVV","VVD","NSC","BBB"]',
    92,
    'centrum-rechts',
    '["GL-PvdA","D66","Volt","SP","CDA","DENK","Nederland Vooruit (NV)"]',
    'Dick Schoof',
    'Onafhankelijk',
    'Schoof II',
    'centrum-rechts',
    150,
    10524000,
    80.1,
    0.67,
    '2025-03-19',
    '2025-05-20',
    NULL,
    62,
    'kabinetsval',
    '["Immigratie","Woningmarkt","Energiezekerheid","Veiligheid","Zorg"]',
    'De verkiezingen kwamen er nadat het extraparlementaire kabinet van Schoof verviel door interne ruzies over het asielbeleid. Dat leidde tot vervroegde stembusgang met felle onderhandelingen om een meerderheidscoalitie.',
    'PVV verzamelde de meeste zetels sinds 2002 en Nederland Vooruit (NV) haalde de kiesdrempel met slechts 1,6 procent.',
    '["Nederland Vooruit (NV)"]',
    '["50PLUS"]',
    'PVV',
    4,
    'GL-PvdA',
    -3,
    12,
    '["Volt","JA21","Nederland Vooruit (NV)"]',
    '["BIJ1","50PLUS"]',
    '[{"naam":"Geert Wilders","partij":"PVV"},{"naam":"Mark Rutte","partij":"VVD"},{"naam":"Lilianne Ploumen","partij":"GL-PvdA"},{"naam":"Sigrid Kaag","partij":"D66"}]',
    '[{"naam":"RTL Nieuws Verkiezingsdebat","youtube_url":"https://www.youtube.com/watch?v=2Z4m4lnjxkY"},{"naam":"NOS Verkiezingsdebat","youtube_url":"https://www.youtube.com/watch?v=1w7OgIMMRc4"},{"naam":"PolitiekPraat Live Debat","youtube_url":"https://www.youtube.com/watch?v=XYzK1q5B0IM"}]',
    '01:58:00',
    2.3,
    'In maart 2025 kozen kiezers voor een coalitie die asiel, woningmarkt en energie wilde doorbreken. PVV werd de grootste partij en ging een centrum-rechts verbond aan met VVD, NSC en BBB onder leiding van Dick Schoof.',
    '["NOS","Kiesraad","PolitiekPraat research"]',
    'https://politiekpraat.nl/images/verkiezingen-2025.jpg'
);
