<?php
require_once dirname(__DIR__) . '/includes/config.php';
require_once dirname(__DIR__) . '/includes/Database.php';

echo "=== Volledige Nederlandse Politieke Database Migratie (1848-heden) ===\n\n";

try {
    $database = new Database();
    $pdo = $database->getConnection();

    echo "Database verbinding succesvol...\n";

    // --- TABELLEN AANMAKEN ---
    $mpMigrationFile = dirname(__DIR__) . '/database/migrations/create_nederlandse_ministers_presidenten_table.sql';
    if (file_exists($mpMigrationFile)) {
        $pdo->exec(file_get_contents($mpMigrationFile));
        echo "✓ Nederlandse ministers-presidenten tabel aangemaakt\n";
    } else {
        echo "! Ministers-presidenten migratie bestand niet gevonden: $mpMigrationFile\n";
    }

    $verkiezingenMigrationFile = dirname(__DIR__) . '/database/migrations/create_nederlandse_verkiezingen_table.sql';
    if (file_exists($verkiezingenMigrationFile)) {
        $pdo->exec(file_get_contents($verkiezingenMigrationFile));
        echo "✓ Nederlandse verkiezingen tabel aangemaakt\n";
    } else {
        echo "! Verkiezingen migratie bestand niet gevonden: $verkiezingenMigrationFile\n";
    }

    echo "\nGegevens toevoegen...\n";

    // --- DATA MINISTERS-PRESIDENTEN ---

    $ministers_presidenten = [
        ['nummer' => 1, 'naam' => 'Dick Schoof', 'volledige_naam' => 'Hendrikus Wilhelmus Maria Schoof', 'partij' => 'Onafhankelijk', 'start' => '2024-07-02', 'eind' => null, 'huidig' => 1, 'geboren' => '1957-03-08', 'overleden' => null, 'geboorteplaats' => 'Santpoort', 'bio' => 'Voormalig topambtenaar die na de verkiezingen van 2023 een extraparlementair kabinet leidt.', 'leeftijd' => 67, 'vroeg_leven' => 'Opgegroeid in een katholiek gezin van acht kinderen.', 'carriere' => 'Lange carrière in de ambtenarij, o.a. als directeur-generaal AIVD en NCTV.', 'prestaties' => ['Eerste politiek onafhankelijke premier sinds Cort van der Linden'], 'fun_facts' => ['Is een fervent hardloper.'], 'echtgenoot' => 'Yolanda Senf', 'kinderen' => ['Twee dochters'], 'kabinetten' => ['Schoof'], 'coalitie' => ['PVV', 'VVD', 'NSC', 'BBB'], 'gebeurtenissen' => 'Langste formatie sinds 1977, vorming van een extraparlementair kabinet.', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => 'Hoge inflatie, woningtekort, stikstofcrisis.', 'carriere_voor' => 'Secretaris-generaal van het ministerie van Justitie en Veiligheid (2020-2024).', 'waardering' => 'Nog te bepalen.', 'controverses' => 'Zijn rol als hoofd van de AIVD en NCTV in diverse dossiers.', 'citaten' => [], 'onderwijs' => 'Planologie (Katholieke Universiteit Nijmegen)', 'ministersposten' => [], 'foto' => 'https://upload.wikimedia.org/wikipedia/commons/2/23/Dick_Schoof_%282024%29.jpg'],
        ['nummer' => 50, 'naam' => 'Mark Rutte', 'volledige_naam' => 'Mark Rutte', 'partij' => 'VVD', 'start' => '2010-10-14', 'eind' => '2024-07-02', 'huidig' => 0, 'geboren' => '1967-02-14', 'overleden' => null, 'geboorteplaats' => 'Den Haag', 'bio' => 'Mark Rutte was de langstzittende minister-president van Nederland. Hij leidde vier kabinetten en was bekend om zijn pragmatische bestuursstijl en crisismanagement.', 'leeftijd' => 43, 'vroeg_leven' => 'Geboren in Den Haag als zoon van een importeur. Groeide op in een liberaal gezin en toonde vroeg interesse in politiek.', 'carriere' => 'Begon als junior consultant bij Unilever, werd VVD-kamerlid in 2002, staatssecretaris Onderwijs in 2004, VVD-fractievoorzitter in 2006.', 'prestaties' => ['Langstzittende minister-president ooit (13+ jaar)', 'Leidde Nederland door 4 verschillende crises', 'Vormde 4 verschillende kabinetten', 'Moderniseerde de VVD'], 'fun_facts' => ['Fietst elke dag naar het Torentje', 'Heeft geen rijbewijs', 'Kan geen computer typen', 'Drinkt 8-10 koppen koffie per dag', 'Spreekt vloeiend Engels, Duits en Frans'], 'echtgenoot' => 'Ongehuwd', 'kinderen' => [], 'kabinetten' => ['Rutte I (2010-2012)', 'Rutte II (2012-2017)', 'Rutte III (2017-2021)', 'Rutte IV (2022-2024)'], 'coalitie' => ['CDA', 'PvdA', 'D66', 'ChristenUnie', 'PVV (gedoogsteun)'], 'gebeurtenissen' => 'Eurocrisis, COVID-19 pandemie, Klimaatakkoord, MH17, Toeslagenaffaire, val van Rutte IV over immigratie', 'speeches' => ['"Nederland kan dit aan" (COVID-19)', '"De lat ligt hoog" (klimaat)', '"Lekker belangrijk" (over kritiek)'], 'wetgeving' => ['Klimaatwet', 'Pensioenwet', 'Coronasteunpakketten', 'Infrastructuurprogramma'], 'crises' => ['Eurocrisis (2010-2015)', 'COVID-19 pandemie (2020-2022)', 'Toeslagenaffaire (2019-2021)', 'Immigratiecrisis (2023)'], 'economie' => 'Leidde Nederland door economische groei, lage werkloosheid, maar ook toenemende ongelijkheid en woningcrisis', 'carriere_voor' => 'Historicus bij Universiteit Leiden, staatssecretaris Onderwijs (2004-2006), VVD-fractievoorzitter (2006-2010)', 'waardering' => 'Beschouwd als pragmatische leider die Nederland door multiple crises loodste, maar bekritiseerd om toeslagenaffaire en bestuurscultuur.', 'controverses' => 'Toeslagenaffaire, bestuurscultuur Den Haag, omgang met Tweede Kamer informatie', 'citaten' => ['Laat ik heel duidelijk zijn', 'Nederland kan dit aan', 'De lat ligt hoog', 'Lekker belangrijk'], 'onderwijs' => 'Geschiedenis (Universiteit Leiden)', 'ministersposten' => ['Staatssecretaris van Sociale Zaken en Werkgelegenheid (2002-2004)', 'Staatssecretaris van Onderwijs, Cultuur en Wetenschap (2004-2006)'], 'foto' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Mark_Rutte_2015_%28cropped%29.jpg/256px-Mark_Rutte_2015_%28cropped%29.jpg'],
        ['nummer' => 49, 'naam' => 'Jan Peter Balkenende', 'volledige_naam' => 'Jan Peter Balkenende', 'partij' => 'CDA', 'start' => '2002-07-22', 'eind' => '2010-10-14', 'huidig' => 0, 'geboren' => '1956-05-07', 'overleden' => null, 'geboorteplaats' => 'Kapelle', 'bio' => 'Jan Peter Balkenende leidde vier kabinetten tijdens een turbulente periode met economische crisis en politieke versnippering. Bekend om zijn christelijke waarden en nuchtere aanpak.', 'leeftijd' => 46, 'vroeg_leven' => 'Opgegroeid in christelijk gezin in Zeeland. Toonde vroeg interesse in economie en politiek, actief in studentenverenigingen.', 'carriere' => 'Econoom, universitair docent, CDA-kamerlid vanaf 1998, werd partijleider na verkiezingsoverwinning 2002.', 'prestaties' => ['Eerste CDA-premier sinds Lubbers', 'Leidde Nederland door economische crisis 2008', 'Vormde 4 verschillende kabinetten', 'Moderniseerde het CDA'], 'fun_facts' => ['Droeg altijd een Harry Potter-bril', 'Was professor economie voor hij premier werd', 'Sprak vloeiend Duits vanwege Duitse moeder'], 'echtgenoot' => 'Bianca Hoogendijk', 'kinderen' => ['Amelie'], 'kabinetten' => ['Balkenende I (2002)', 'Balkenende II (2003-2006)', 'Balkenende III (2006-2007)', 'Balkenende IV (2007-2010)'], 'coalitie' => ['LPF', 'VVD', 'D66', 'PvdA', 'ChristenUnie'], 'gebeurtenissen' => 'Moord Fortuyn, Irakoorlog, Cartooncrisis, Financiële crisis 2008, Val kabinet-Balkenende IV', 'speeches' => ['"We gaan met elkaar de schouders eronder zetten" (crisis)', '"Aan de slag" (motto)', '"VOC-mentaliteit"'], 'wetgeving' => ['Wet werk en bijstand', 'Zorgstelselhervorming', 'Crisismaatregelen 2008'], 'crises' => ['Financiële crisis (2008-2010)', 'Politieke instabiliteit (2002-2010)', 'Integratiedebat', 'Irakoorlog controverse'], 'economie' => 'Leidde Nederland door periode van economische groei gevolgd door crisis, politieke turbulentie na Fortuyn', 'carriere_voor' => 'Universitair docent economie (VU Amsterdam), CDA-kamerlid (1998-2002)', 'waardering' => 'Beschouwd als betrouwbare crisismanager, maar geplaagd door politieke instabiliteit en korte kabinetten', 'controverses' => 'Irakoorlog steun, omgang met LPF, Srebrenica-rapport, bankiersbonussen crisis', 'citaten' => ['Aan de slag', 'We gaan met elkaar de schouders eronder zetten', 'Nederland verdient beter'], 'onderwijs' => 'Geschiedenis en Rechten (VU Amsterdam)', 'ministersposten' => [], 'foto' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Jan_Peter_Balkenende_2008.jpg/256px-Jan_Peter_Balkenende_2008.jpg'],
        ['nummer' => 48, 'naam' => 'Wim Kok', 'volledige_naam' => 'Willem Kok', 'partij' => 'PvdA', 'start' => '1994-08-22', 'eind' => '2002-07-22', 'huidig' => 0, 'geboren' => '1938-09-29', 'overleden' => '2018-10-20', 'geboorteplaats' => 'Bergambacht', 'bio' => 'Wim Kok was minister-president tijdens de economische bloeiperiode van de jaren negentig. Bekend van de paarse kabinetten en de polderconsensus.', 'leeftijd' => 55, 'vroeg_leven' => 'Opgegroeid in een arbeidersgezin. Verliet school vroeg en werd bankemployé.', 'carriere' => 'Vakbondsleider (NVV, FNV), PvdA-voorzitter, minister Financiën (1989-1994) voor hij premier werd.', 'prestaties' => ['Leidde de paarse kabinetten (PvdA-VVD-D66)', 'Nederland door economische bloei jaren 90', 'Poldermodel internationaal voorbeeld', 'Werkloosheid daalde naar historisch laag niveau'], 'fun_facts' => ['Begon als bankbediende zonder diploma', 'Was een fervent jazzliefhebber', 'Sprak altijd van wij nooit van ik'], 'echtgenoot' => 'Rita Roukens', 'kinderen' => ['André', 'Marcel', 'Carla'], 'kabinetten' => ['Kok I (1994-1998)', 'Kok II (1998-2002)'], 'coalitie' => ['VVD', 'D66'], 'gebeurtenissen' => 'Srebrenica (1995), EU-integratie, Euro-invoering, Kosovo-oorlog, Bijlmerramp onderzoek', 'speeches' => ['"Nederland kan trots zijn" (afscheid)', '"Paars werkt" (verkiezingen)'], 'wetgeving' => ['Flexwet', 'AOW-hervorming', 'Belastingherziening 2001', 'WAO-hervorming'], 'crises' => ['Srebrenica-crisis (1995) en aftreden kabinet', 'Bijlmerramp-onderzoek', 'BSE-crisis'], 'economie' => 'Leidde Nederland door gouden economische jaren: hoge groei, dalende werkloosheid, begrotingsoverschotten', 'carriere_voor' => 'Vakbondsbestuurder FNV (1973-1986), PvdA-fractievoorzitter (1986-1989), minister van Financiën (1989-1994)', 'waardering' => 'Beschouwd als een van de succesvolste naoorlogse premiers, architect van het poldermodel.', 'controverses' => 'Srebrenica-rapport en aftreden kabinet, afbouw sociale zekerheid.', 'citaten' => ['Paars werkt', 'Nederland kan trots zijn', 'Excuus, excuus, excuus'], 'onderwijs' => 'Nijenrode Business Universiteit (niet afgemaakt)', 'ministersposten' => ['Minister van Financiën (1989-1994)'], 'foto' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Wim_Kok_1994.jpg/256px-Wim_Kok_1994.jpg'],
        ['nummer' => 47, 'naam' => 'Ruud Lubbers', 'volledige_naam' => 'Rudolphus Franciscus Marie Lubbers', 'partij' => 'CDA', 'start' => '1982-11-04', 'eind' => '1994-08-22', 'huidig' => 0, 'geboren' => '1939-05-07', 'overleden' => '2018-02-14', 'geboorteplaats' => 'Rotterdam', 'bio' => 'Langstzittende premier na Rutte. Stond bekend om zijn "no-nonsense" bezuinigingsbeleid.', 'leeftijd' => 43, 'vroeg_leven' => '', 'carriere' => 'Ondernemer, minister van Economische Zaken, fractievoorzitter CDA.', 'prestaties' => ['Ombuigen van begrotingstekorten', 'Hervorming sociale zekerheid (WAO)', 'Verdrag van Maastricht (EU)'], 'fun_facts' => [], 'echtgenoot' => 'Ria Hoogeweegen', 'kinderen' => ['Paul', 'Bart', 'Heleen'], 'kabinetten' => ['Lubbers I', 'Lubbers II', 'Lubbers III'], 'coalitie' => ['VVD', 'PvdA'], 'gebeurtenissen' => 'Economische crisis jaren 80, kruisrakettendebat, val van de Berlijnse Muur.', 'speeches' => [], 'wetgeving' => ['Akkoord van Wassenaar', 'WAO-herziening'], 'crises' => ['Economische crisis begin jaren 80', 'Kruisrakettencrisis'], 'economie' => 'Herstel van de economie, maar ook stijgende werkloosheid.', 'carriere_voor' => 'Directeur Hollandia-Kloos, Minister van Economische Zaken (1973-1977)', 'waardering' => 'Gerespecteerd als crisismanager en staatsman.', 'controverses' => 'Affaire rond seksuele intimidatie bij de UNHCR.', 'citaten' => ['Meer markt, minder overheid'], 'onderwijs' => 'Economie (Nederlandse Economische Hogeschool)', 'ministersposten' => ['Minister van Economische Zaken (1973-1977)'], 'foto' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Ruud_Lubbers_%281983%29.jpg/256px-Ruud_Lubbers_%281983%29.jpg'],
        ['nummer' => 46, 'naam' => 'Dries van Agt', 'volledige_naam' => 'Andreas Antonius Maria van Agt', 'partij' => 'CDA', 'start' => '1977-12-19', 'eind' => '1982-11-04', 'huidig' => 0, 'geboren' => '1931-02-02', 'overleden' => '2024-02-05', 'geboorteplaats' => 'Geldrop', 'bio' => 'Eerste premier van het CDA. Stond bekend om zijn bloemrijke taalgebruik.', 'leeftijd' => 46, 'vroeg_leven' => '', 'carriere' => 'Jurist, hoogleraar, minister van Justitie.', 'prestaties' => ['Vorming van het CDA'], 'fun_facts' => ['Was een fervent wielrenner'], 'echtgenoot' => 'Eugenie Krekelberg', 'kinderen' => ['Eugenie', 'Frans', 'Caroline'], 'kabinetten' => ['Van Agt I', 'Van Agt II', 'Van Agt III'], 'coalitie' => ['VVD', 'PvdA', 'D66'], 'gebeurtenissen' => 'Economische crisis eind jaren 70, Molukse treinkapingen.', 'speeches' => [], 'wetgeving' => ["Bestek'81 (bezuinigingsplan)"], 'crises' => ['Economische recessie', 'Hoge werkloosheid', 'Molukse acties'], 'economie' => 'Stagnerende economie en oplopende staatsschuld.', 'carriere_voor' => 'Hoogleraar strafrecht, Minister van Justitie (1971-1977)', 'waardering' => 'Bewonderd om zijn intellect, bekritiseerd om zijn polariserende rol.', 'controverses' => 'De "zaak-Menten".', 'citaten' => ['Ik ben een democraat in merg en been'], 'onderwijs' => 'Rechten (Katholieke Universiteit Nijmegen)', 'ministersposten' => ['Minister van Justitie (1971-1977)'], 'foto' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Dries_van_Agt_%281977%29.jpg/256px-Dries_van_Agt_%281977%29.jpg'],
        ['nummer' => 45, 'naam' => 'Joop den Uyl', 'volledige_naam' => 'Johannes Marten den Uijl', 'partij' => 'PvdA', 'start' => '1973-05-11', 'eind' => '1977-12-19', 'huidig' => 0, 'geboren' => '1919-08-09', 'overleden' => '1987-12-24', 'geboorteplaats' => 'Hilversum', 'bio' => 'Leider van het meest progressieve kabinet uit de Nederlandse geschiedenis.', 'leeftijd' => 53, 'vroeg_leven' => '', 'carriere' => 'Econoom, journalist, wethouder, minister van Economische Zaken.', 'prestaties' => ['Spreiding van kennis, macht en inkomen'], 'fun_facts' => [], 'echtgenoot' => 'Liesbeth van Vessem', 'kinderen' => ['Saskia', 'Xander', 'Barbara', 'Martijn', 'Art', 'Jeroen'], 'kabinetten' => ['Den Uyl'], 'coalitie' => ['KVP', 'ARP', 'D66', 'PPR'], 'gebeurtenissen' => 'Oliecrisis van 1973, autoloze zondagen, affaire-Lockheed.', 'speeches' => ['De verbeelding aan de macht'], 'wetgeving' => ['Wet op de Investeringsrekening (WIR)'], 'crises' => ['Oliecrisis (1973)', 'Lockheed-affaire'], 'economie' => 'Aanvankelijk groei, later stagnatie (stagflatie).', 'carriere_voor' => 'Wethouder Amsterdam, Minister van Economische Zaken (1965-1967)', 'waardering' => 'Iconische, maar ook polariserende premier.', 'controverses' => 'Zijn polariserende stijl en de Lockheed-affaire.', 'citaten' => ['De verbeelding aan de macht'], 'onderwijs' => 'Economie (Universiteit van Amsterdam)', 'ministersposten' => ['Minister van Economische Zaken (1965-1967)'], 'foto' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Joop_den_Uyl_%281973%29.jpg/256px-Joop_den_Uyl_%281973%29.jpg'],
        ['nummer' => 44, 'naam' => 'Barend Biesheuvel', 'volledige_naam' => 'Barend Willem Biesheuvel', 'partij' => 'ARP', 'start' => '1971-07-06', 'eind' => '1973-05-11', 'huidig' => 0, 'geboren' => '1920-04-05', 'overleden' => '2001-04-29', 'geboorteplaats' => 'Haarlemmerliede', 'bio' => 'Leidde twee kortstondige kabinetten in een politiek onrustige tijd.', 'leeftijd' => 51, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Biesheuvel I', 'Biesheuvel II'], 'coalitie' => ['KVP', 'VVD', 'CHU', 'DS\'70'], 'gebeurtenissen' => 'Val van het kabinet door onenigheid over bezuinigingen.', 'speeches' => [], 'wetgeving' => [], 'crises' => ['Interne kabinetscrisis'], 'economie' => '', 'carriere_voor' => '', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Vrije Universiteit Amsterdam)', 'ministersposten' => ['Minister van Landbouw en Visserij'], 'foto' => ''],
        ['nummer' => 43, 'naam' => 'Piet de Jong', 'volledige_naam' => 'Petrus Jozef Sietse de Jong', 'partij' => 'KVP', 'start' => '1967-04-05', 'eind' => '1971-07-06', 'huidig' => 0, 'geboren' => '1915-04-03', 'overleden' => '2016-07-27', 'geboorteplaats' => 'Apeldoorn', 'bio' => 'Zat als eerste naoorlogse premier de volledige periode uit. Zijn kabinet wordt gezien als succesvol.', 'leeftijd' => 52, 'vroeg_leven' => '', 'carriere' => 'Officier onderzeedienst, staatssecretaris en minister van Defensie.', 'prestaties' => ['Maakte de regeringsperiode vol', 'Modernisering van beleid'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['De Jong'], 'coalitie' => ['VVD', 'ARP', 'CHU'], 'gebeurtenissen' => 'Studentenprotesten (Maagdenhuisbezetting).', 'speeches' => [], 'wetgeving' => ['Mammoetwet'], 'crises' => [], 'economie' => 'Periode van economische voorspoed en culturele veranderingen.', 'carriere_voor' => 'Minister van Defensie', 'waardering' => 'Hoog gewaardeerd voor zijn daadkrachtige en pragmatische stijl.', 'controverses' => '', 'citaten' => [], 'onderwijs' => '', 'ministersposten' => ['Minister van Defensie'], 'foto' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Piet_de_Jong_%281967%29.jpg/256px-Piet_de_Jong_%281967%29.jpg'],
        ['nummer' => 42, 'naam' => 'Jelle Zijlstra', 'volledige_naam' => 'Jelle Zijlstra', 'partij' => 'ARP', 'start' => '1966-11-22', 'eind' => '1967-04-05', 'huidig' => 0, 'geboren' => '1918-08-27', 'overleden' => '2001-12-23', 'geboorteplaats' => 'Oosterbierum', 'bio' => 'Leidde een interim-kabinet na de val van het kabinet-Cals.', 'leeftijd' => 48, 'vroeg_leven' => '', 'carriere' => 'Hoogleraar economie, minister van Economische Zaken en Financiën.', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Zijlstra'], 'coalitie' => ['KVP', 'ARP'], 'gebeurtenissen' => 'Overbruggingsperiode naar nieuwe verkiezingen.', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Financiën', 'waardering' => 'Werd later president van De Nederlandsche Bank.', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Economie (Nederlandse Economische Hogeschool)', 'ministersposten' => ['Minister van Financiën'], 'foto' => ''],
        ['nummer' => 41, 'naam' => 'Jo Cals', 'volledige_naam' => 'Jozef Maria Laurens Theo Cals', 'partij' => 'KVP', 'start' => '1965-04-14', 'eind' => '1966-11-22', 'huidig' => 0, 'geboren' => '1914-07-18', 'overleden' => '1971-12-30', 'geboorteplaats' => 'Roermond', 'bio' => 'Kabinet-Cals viel tijdens de "Nacht van Schmelzer" over de begroting.', 'leeftijd' => 50, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Cals'], 'coalitie' => ['PvdA', 'ARP'], 'gebeurtenissen' => 'Nacht van Schmelzer.', 'speeches' => [], 'wetgeving' => [], 'crises' => ['Nacht van Schmelzer'], 'economie' => '', 'carriere_voor' => 'Minister van Onderwijs', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Katholieke Universiteit Nijmegen)', 'ministersposten' => ['Minister van Onderwijs, Kunsten en Wetenschappen'], 'foto' => ''],
        ['nummer' => 40, 'naam' => 'Victor Marijnen', 'volledige_naam' => 'Victor Gerard Marie Marijnen', 'partij' => 'KVP', 'start' => '1963-07-24', 'eind' => '1965-04-14', 'huidig' => 0, 'geboren' => '1917-02-21', 'overleden' => '1975-04-05', 'geboorteplaats' => 'Arnhem', 'bio' => 'Kabinet viel door onenigheid over het omroepbestel.', 'leeftijd' => 46, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Marijnen'], 'coalitie' => ['VVD', 'ARP', 'CHU'], 'gebeurtenissen' => 'Val van het kabinet over het omroepbestel.', 'speeches' => [], 'wetgeving' => [], 'crises' => ['Omroepcrisis'], 'economie' => '', 'carriere_voor' => 'Minister van Landbouw', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Katholieke Universiteit Nijmegen)', 'ministersposten' => ['Minister van Landbouw en Visserij'], 'foto' => ''],
        ['nummer' => 39, 'naam' => 'Jan de Quay', 'volledige_naam' => 'Jan Eduard de Quay', 'partij' => 'KVP', 'start' => '1959-05-19', 'eind' => '1963-07-24', 'huidig' => 0, 'geboren' => '1901-08-26', 'overleden' => '1985-07-04', 'geboorteplaats' => "'s-Hertogenbosch", 'bio' => 'Leidde het eerste kabinet na het Drees-tijdperk.', 'leeftijd' => 57, 'vroeg_leven' => '', 'carriere' => 'Hoogleraar psychologie, commissaris van de Koningin.', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['De Quay'], 'coalitie' => ['VVD', 'ARP', 'CHU'], 'gebeurtenissen' => 'Begin van de gaswinning in Groningen.', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => 'Begin van de "golden sixties".', 'carriere_voor' => 'Commissaris van de Koningin', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Psychologie (Rijksuniversiteit Utrecht)', 'ministersposten' => ['Minister-president in de regering-in-ballingschap'], 'foto' => ''],
        ['nummer' => 38, 'naam' => 'Louis Beel', 'volledige_naam' => 'Louis Joseph Maria Beel', 'partij' => 'KVP', 'start' => '1958-12-22', 'eind' => '1959-05-19', 'huidig' => 0, 'geboren' => '1902-04-12', 'overleden' => '1977-02-11', 'geboorteplaats' => 'Roermond', 'bio' => 'Leidde zijn tweede, korte interim-kabinet.', 'leeftijd' => 56, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Beel II'], 'coalitie' => ['KVP', 'ARP', 'CHU'], 'gebeurtenissen' => 'Overbrugging naar de verkiezingen van 1959.', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Binnenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Katholieke Universiteit Nijmegen)', 'ministersposten' => ['Minister van Binnenlandse Zaken', 'Minister-president (1946-1948)'], 'foto' => ''],
        ['nummer' => 37, 'naam' => 'Willem Drees', 'volledige_naam' => 'Willem Drees', 'partij' => 'PvdA', 'start' => '1948-08-07', 'eind' => '1958-12-22', 'huidig' => 0, 'geboren' => '1886-07-05', 'overleden' => '1988-05-14', 'geboorteplaats' => 'Amsterdam', 'bio' => '"Vadertje Drees", grondlegger van de naoorlogse verzorgingsstaat, met name de AOW.', 'leeftijd' => 62, 'vroeg_leven' => '', 'carriere' => 'Stenograaf, wethouder in Den Haag, fractievoorzitter SDAP.', 'prestaties' => ['Opbouw van de verzorgingsstaat', 'Invoering AOW (1957)', 'Herstel na WOII', 'NAVO-lidmaatschap'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Drees-Van Schaik', 'Drees I', 'Drees II', 'Drees III'], 'coalitie' => ['KVP', 'CHU', 'ARP', 'VVD'], 'gebeurtenissen' => 'Wederopbouw, politionele acties in Indonesië, Koude Oorlog, watersnoodramp (1953).', 'speeches' => [], 'wetgeving' => ['Algemene Ouderdomswet (AOW)'], 'crises' => ['Dekolonisatie Indonesië', 'Watersnoodramp 1953'], 'economie' => 'Wederopbouw en economische groei.', 'carriere_voor' => 'Minister van Sociale Zaken', 'waardering' => 'Wordt gezien als een van de belangrijkste politici uit de Nederlandse geschiedenis.', 'controverses' => '', 'citaten' => ['De man van de AOW'], 'onderwijs' => '', 'ministersposten' => ['Minister van Sociale Zaken'], 'foto' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Willem_Drees_%281949%29.jpg/256px-Willem_Drees_%281949%29.jpg'],
        ['nummer' => 36, 'naam' => 'Louis Beel', 'volledige_naam' => 'Louis Joseph Maria Beel', 'partij' => 'KVP', 'start' => '1946-07-03', 'eind' => '1948-08-07', 'huidig' => 0, 'geboren' => '1902-04-12', 'overleden' => '1977-02-11', 'geboorteplaats' => 'Roermond', 'bio' => 'Leidde het eerste naoorlogse kabinet na verkiezingen.', 'leeftijd' => 44, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Beel I'], 'coalitie' => ['PvdA'], 'gebeurtenissen' => 'Start van de politionele acties.', 'speeches' => [], 'wetgeving' => [], 'crises' => ['Politionele acties'], 'economie' => 'Wederopbouw', 'carriere_voor' => 'Minister van Binnenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Katholieke Universiteit Nijmegen)', 'ministersposten' => ['Minister van Binnenlandse Zaken'], 'foto' => ''],
        ['nummer' => 35, 'naam' => 'Wim Schermerhorn', 'volledige_naam' => 'Willem Schermerhorn', 'partij' => 'PvdA', 'start' => '1945-06-24', 'eind' => '1946-07-03', 'huidig' => 0, 'geboren' => '1894-12-17', 'overleden' => '1977-03-10', 'geboorteplaats' => 'Akersloot', 'bio' => 'Eerste minister-president na de bevrijding. Leidde een "noodkabinet" om het land te besturen.', 'leeftijd' => 50, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Herstel van het gezag na WOII', 'Oprichting PvdA'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Schermerhorn-Drees'], 'coalitie' => ['VDB', 'SDAP', 'RKSP', 'ARP', 'CHU'], 'gebeurtenissen' => 'Naoorlogse wederopbouw, begin van de Indonesische onafhankelijkheidsstrijd.', 'speeches' => [], 'wetgeving' => [], 'crises' => ['Indonesische kwestie'], 'economie' => 'Land in puin na de oorlog.', 'carriere_voor' => 'Hoogleraar landmeetkunde', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Hoogleraar landmeetkunde', 'ministersposten' => [], 'foto' => ''],
        ['nummer' => 34, 'naam' => 'Pieter Gerbrandy', 'volledige_naam' => 'Pieter Sjoerds Gerbrandy', 'partij' => 'ARP', 'start' => '1940-09-03', 'eind' => '1945-06-24', 'huidig' => 0, 'geboren' => '1885-04-13', 'overleden' => '1961-09-07', 'geboorteplaats' => 'Goënga', 'bio' => 'Minister-president van de Nederlandse regering in ballingschap in Londen tijdens WOII.', 'leeftijd' => 55, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Leiding aan de regering in ballingschap', 'Radio Oranje-toespraken'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Gerbrandy I', 'Gerbrandy II', 'Gerbrandy III'], 'coalitie' => [], 'gebeurtenissen' => 'Tweede Wereldoorlog.', 'speeches' => ['Maar de koningin is in het land!'], 'wetgeving' => [], 'crises' => ['Tweede Wereldoorlog'], 'economie' => '', 'carriere_voor' => 'Minister van Justitie', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Vrije Universiteit Amsterdam)', 'ministersposten' => ['Minister van Justitie'], 'foto' => ''],
        ['nummer' => 33, 'naam' => 'Dirk Jan de Geer', 'volledige_naam' => 'Dirk Jan de Geer', 'partij' => 'CHU', 'start' => '1939-08-10', 'eind' => '1940-09-03', 'huidig' => 0, 'geboren' => '1870-12-14', 'overleden' => '1960-11-28', 'geboorteplaats' => 'Groningen', 'bio' => 'Leidde het laatste kabinet voor de Duitse inval. Werd ontslagen vanwege zijn defaitistische houding.', 'leeftijd' => 68, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['De Geer II'], 'coalitie' => [], 'gebeurtenissen' => 'Duitse inval in Nederland (mei 1940).', 'speeches' => [], 'wetgeving' => [], 'crises' => ['Tweede Wereldoorlog'], 'economie' => 'Mobilisatie en economische voorbereiding op oorlog.', 'carriere_voor' => 'Minister van Financiën', 'waardering' => 'Zeer negatief vanwege zijn pleidooi voor een afzonderlijke vrede met Duitsland.', 'controverses' => 'Werd na de oorlog veroordeeld voor landverraad in tijd van oorlog.', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Utrecht)', 'ministersposten' => ['Minister van Financiën', 'Minister-president (1926-1929)'], 'foto' => ''],
        ['nummer' => 32, 'naam' => 'Hendrikus Colijn', 'volledige_naam' => 'Hendrikus Colijn', 'partij' => 'ARP', 'start' => '1933-05-26', 'eind' => '1939-08-10', 'huidig' => 0, 'geboren' => '1869-06-22', 'overleden' => '1944-09-18', 'geboorteplaats' => 'Burgerveen', 'bio' => 'Dominante politicus van het interbellum. Leidde vijf kabinetten.', 'leeftijd' => 63, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Crisisbeleid in de jaren 30 (aanpassingspolitiek)'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Colijn II', 'Colijn III', 'Colijn IV', 'Colijn V'], 'coalitie' => [], 'gebeurtenissen' => 'Grote Depressie, opkomst van het fascisme en nazisme.', 'speeches' => [], 'wetgeving' => ['Aanpassingspolitiek'], 'crises' => ['Economische wereldcrisis'], 'economie' => 'Zware economische crisis met hoge werkloosheid.', 'carriere_voor' => 'Minister van Oorlog', 'waardering' => 'Gerespecteerd als sterke leider, maar zijn crisisbeleid wordt bekritiseerd als te star.', 'controverses' => '', 'citaten' => ['Ik ga rustig slapen'], 'onderwijs' => '', 'ministersposten' => ['Minister van Oorlog', 'Minister van Financiën'], 'foto' => ''],
        ['nummer' => 31, 'naam' => 'Charles Ruijs de Beerenbrouck', 'volledige_naam' => 'Charles Joseph Maria Ruijs de Beerenbrouck', 'partij' => 'RKSP', 'start' => '1929-08-10', 'eind' => '1933-05-26', 'huidig' => 0, 'geboren' => '1873-12-01', 'overleden' => '1936-04-17', 'geboorteplaats' => 'Roermond', 'bio' => 'Leidde zijn derde kabinet aan het begin van de wereldwijde economische crisis.', 'leeftijd' => 55, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Ruijs de Beerenbrouck III'], 'coalitie' => [], 'gebeurtenissen' => 'Beurskrach van 1929 en begin van de Grote Depressie.', 'speeches' => [], 'wetgeving' => [], 'crises' => ['Economische wereldcrisis'], 'economie' => 'Begin van de crisisjaren.', 'carriere_voor' => 'Minister-president (1918-1925)', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Leiden)', 'ministersposten' => ['Minister-president (1918-1925)'], 'foto' => ''],
        ['nummer' => 30, 'naam' => 'Dirk Jan de Geer', 'volledige_naam' => 'Dirk Jan de Geer', 'partij' => 'CHU', 'start' => '1926-03-08', 'eind' => '1929-08-10', 'huidig' => 0, 'geboren' => '1870-12-14', 'overleden' => '1960-11-28', 'geboorteplaats' => 'Groningen', 'bio' => 'Leidde zijn eerste kabinet in een periode van relatieve economische stabiliteit.', 'leeftijd' => 55, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['De Geer I'], 'coalitie' => [], 'gebeurtenissen' => 'Periode van de "roaring twenties".', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => 'Relatieve economische voorspoed.', 'carriere_voor' => 'Minister van Financiën', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Utrecht)', 'ministersposten' => ['Minister van Financiën'], 'foto' => ''],
        ['nummer' => 29, 'naam' => 'Hendrikus Colijn', 'volledige_naam' => 'Hendrikus Colijn', 'partij' => 'ARP', 'start' => '1925-08-04', 'eind' => '1926-03-08', 'huidig' => 0, 'geboren' => '1869-06-22', 'overleden' => '1944-09-18', 'geboorteplaats' => 'Burgerveen', 'bio' => 'Zijn eerste kabinet was zeer kortstondig en viel over het "Gezantschap bij de Paus".', 'leeftijd' => 56, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Colijn I'], 'coalitie' => [], 'gebeurtenissen' => 'Val van het kabinet door de "Nacht van Kersten".', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Oorlog', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => '', 'ministersposten' => ['Minister van Oorlog'], 'foto' => ''],
        ['nummer' => 28, 'naam' => 'Charles Ruijs de Beerenbrouck', 'volledige_naam' => 'Charles Joseph Maria Ruijs de Beerenbrouck', 'partij' => 'RKSP', 'start' => '1918-09-09', 'eind' => '1925-08-04', 'huidig' => 0, 'geboren' => '1873-12-01', 'overleden' => '1936-04-17', 'geboorteplaats' => 'Roermond', 'bio' => 'Eerste katholieke premier en eerste premier na de invoering van het algemeen kiesrecht.', 'leeftijd' => 44, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Invoering 8-urige werkdag', 'Sociale wetgeving'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Ruijs de Beerenbrouck I', 'Ruijs de Beerenbrouck II'], 'coalitie' => ['CHU', 'ARP'], 'gebeurtenissen' => 'Invoering algemeen mannen- en vrouwenkiesrecht, "Vergissing van Troelstra".', 'speeches' => [], 'wetgeving' => ['Arbeidswet 1919'], 'crises' => ['Sociale onrust na WOI'], 'economie' => 'Economische en sociale wederopbouw na WOI.', 'carriere_voor' => '', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Leiden)', 'ministersposten' => [], 'foto' => ''],
        ['nummer' => 27, 'naam' => 'Pieter Cort van der Linden', 'volledige_naam' => 'Pieter Wilhelm Adrianus Cort van der Linden', 'partij' => 'Liberaal', 'start' => '1913-08-29', 'eind' => '1918-09-09', 'huidig' => 0, 'geboren' => '1846-05-14', 'overleden' => '1935-07-15', 'geboorteplaats' => 'Den Haag', 'bio' => 'Leidde Nederland door de Eerste Wereldoorlog en loodste de pacificatie van 1917 door het parlement.', 'leeftijd' => 67, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Nederland neutraal gehouden in WOI', 'Pacificatie van 1917'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Cort van der Linden'], 'coalitie' => [], 'gebeurtenissen' => 'Eerste Wereldoorlog, Pacificatie van 1917.', 'speeches' => [], 'wetgeving' => ['Kieswetherziening', 'Schoolwet'], 'crises' => ['Eerste Wereldoorlog'], 'economie' => 'Economische schaarste en distributie door de oorlog.', 'carriere_voor' => 'Minister van Justitie', 'waardering' => 'Hoog gewaardeerd als staatsman.', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Leiden)', 'ministersposten' => ['Minister van Justitie'], 'foto' => ''],
        ['nummer' => 26, 'naam' => 'Theo Heemskerk', 'volledige_naam' => 'Theodorus Heemskerk', 'partij' => 'ARP', 'start' => '1908-02-12', 'eind' => '1913-08-29', 'huidig' => 0, 'geboren' => '1852-07-20', 'overleden' => '1932-06-12', 'geboorteplaats' => 'Amsterdam', 'bio' => 'Zijn kabinet voerde belangrijke sociale wetgeving door.', 'leeftijd' => 55, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Armenwet', 'Ziektewet'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Heemskerk'], 'coalitie' => [], 'gebeurtenissen' => 'Sociale kwestie.', 'speeches' => [], 'wetgeving' => ['Armenwet 1912'], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Binnenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Leiden)', 'ministersposten' => ['Minister van Binnenlandse Zaken'], 'foto' => ''],
        ['nummer' => 25, 'naam' => 'Theo de Meester', 'volledige_naam' => 'Theodoor Herman de Meester', 'partij' => 'Liberale Unie', 'start' => '1905-08-17', 'eind' => '1908-02-12', 'huidig' => 0, 'geboren' => '1851-12-16', 'overleden' => '1919-12-27', 'geboorteplaats' => 'Harderwijk', 'bio' => 'Kabinet zonder meerderheid in de Kamers, viel over de defensiebegroting.', 'leeftijd' => 53, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['De Meester'], 'coalitie' => [], 'gebeurtenissen' => 'Politieke instabiliteit.', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => '', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => '', 'ministersposten' => [], 'foto' => ''],
        ['nummer' => 24, 'naam' => 'Abraham Kuyper', 'volledige_naam' => 'Abraham Kuyper', 'partij' => 'ARP', 'start' => '1901-08-01', 'eind' => '1905-08-17', 'huidig' => 0, 'geboren' => '1837-10-29', 'overleden' => '1920-11-08', 'geboorteplaats' => 'Maassluis', 'bio' => 'Invloedrijk theoloog, oprichter van de ARP en de Vrije Universiteit.', 'leeftijd' => 63, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Oprichter ARP', 'Stichter Vrije Universiteit', 'Antithese (samenwerking confessionelen)'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Kuyper'], 'coalitie' => [], 'gebeurtenissen' => 'Spoorwegstakingen van 1903.', 'speeches' => [], 'wetgeving' => ['"Worgwetten" (tegen stakingen)'], 'crises' => ['Spoorwegstakingen 1903'], 'economie' => '', 'carriere_voor' => '', 'waardering' => 'Architect van de verzuiling.', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Theologie (Rijksuniversiteit Leiden)', 'ministersposten' => [], 'foto' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Abraham_Kuyper_-_1900.jpg/256px-Abraham_Kuyper_-_1900.jpg'],
        ['nummer' => 23, 'naam' => 'Nicolaas Pierson', 'volledige_naam' => 'Nicolaas Gerard Pierson', 'partij' => 'Liberale Unie', 'start' => '1897-07-27', 'eind' => '1901-08-01', 'huidig' => 0, 'geboren' => '1839-02-07', 'overleden' => '1909-12-24', 'geboorteplaats' => 'Amsterdam', 'bio' => 'Kabinet voerde de Leerplichtwet (1901) en de Woningwet in.', 'leeftijd' => 58, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Leerplichtwet', 'Woningwet'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Pierson'], 'coalitie' => [], 'gebeurtenissen' => 'Sociale kwestie, leerplicht.', 'speeches' => [], 'wetgeving' => ['Leerplichtwet 1900', 'Woningwet 1901'], 'crises' => [], 'economie' => '', 'carriere_voor' => 'President van De Nederlandsche Bank', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Economie', 'ministersposten' => ['Minister van Financiën'], 'foto' => ''],
        ['nummer' => 22, 'naam' => 'Joan Röell', 'volledige_naam' => 'Joan Röell', 'partij' => 'Liberaal', 'start' => '1894-05-09', 'eind' => '1897-07-27', 'huidig' => 0, 'geboren' => '1844-07-21', 'overleden' => '1914-07-13', 'geboorteplaats' => 'Haarlem', 'bio' => 'Kabinet stond bekend om de kieswethervorming van minister Van Houten, die het kiesrecht uitbreidde.', 'leeftijd' => 49, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Kieswet-Van Houten'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Röell'], 'coalitie' => [], 'gebeurtenissen' => 'Kiesrechtkwestie.', 'speeches' => [], 'wetgeving' => ['Kieswet van Van Houten (1896)'], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Buitenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Utrecht)', 'ministersposten' => ['Minister van Buitenlandse Zaken'], 'foto' => ''],
        ['nummer' => 21, 'naam' => 'Gijsbert van Tienhoven', 'volledige_naam' => 'Gijsbert van Tienhoven', 'partij' => 'Liberaal', 'start' => '1891-08-21', 'eind' => '1894-05-09', 'huidig' => 0, 'geboren' => '1841-02-12', 'overleden' => '1914-10-10', 'geboorteplaats' => 'De Werken', 'bio' => 'Kabinet struikelde over een poging tot verdere uitbreiding van het kiesrecht.', 'leeftijd' => 50, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Van Tienhoven'], 'coalitie' => [], 'gebeurtenissen' => 'Kiesrechtkwestie.', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Burgemeester van Amsterdam', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Athenaeum Illustre)', 'ministersposten' => ['Minister van Buitenlandse Zaken'], 'foto' => ''],
        ['nummer' => 20, 'naam' => 'Aeneas Mackay', 'volledige_naam' => 'Aeneas Mackay', 'partij' => 'ARP', 'start' => '1888-04-21', 'eind' => '1891-08-21', 'huidig' => 0, 'geboren' => '1838-11-29', 'overleden' => '1909-11-13', 'geboorteplaats' => 'Nijmegen', 'bio' => 'Eerste kabinet dat steunde op een coalitie van confessionele partijen (ARP en katholieken).', 'leeftijd' => 49, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Eerste confessionele coalitie'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Mackay'], 'coalitie' => ['Katholieken'], 'gebeurtenissen' => 'Schoolstrijd.', 'speeches' => [], 'wetgeving' => ['Schoolwet 1889'], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Binnenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Utrecht)', 'ministersposten' => ['Minister van Binnenlandse Zaken'], 'foto' => ''],
        ['nummer' => 19, 'naam' => 'Jan Heemskerk Azn.', 'volledige_naam' => 'Jan Heemskerk Azn.', 'partij' => 'Conservatief', 'start' => '1883-04-23', 'eind' => '1888-04-21', 'huidig' => 0, 'geboren' => '1818-07-30', 'overleden' => '1897-10-09', 'geboorteplaats' => 'Amsterdam', 'bio' => 'Leidde zijn derde kabinet. Belangrijkste prestatie was de grondwetsherziening van 1887.', 'leeftijd' => 64, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Grondwetsherziening van 1887'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Heemskerk Azn.'], 'coalitie' => [], 'gebeurtenissen' => 'Kiesrechtkwestie, schoolstrijd.', 'speeches' => [], 'wetgeving' => ['Grondwetsherziening 1887'], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Binnenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Athenaeum Illustre)', 'ministersposten' => ['Minister van Binnenlandse Zaken', 'Voorzitter van de Ministerraad (1874-1877)'], 'foto' => ''],
        ['nummer' => 18, 'naam' => 'Theo van Lynden van Sandenburg', 'volledige_naam' => 'Constantijn Theodoor van Lynden van Sandenburg', 'partij' => 'Conservatief-liberaal', 'start' => '1879-08-20', 'eind' => '1883-04-23', 'huidig' => 0, 'geboren' => '1826-02-24', 'overleden' => '1885-11-18', 'geboorteplaats' => 'Utrecht', 'bio' => 'Kabinet probeerde de schoolstrijd en kiesrechtkwestie op te lossen, maar slaagde daar niet volledig in.', 'leeftijd' => 53, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Van Lynden van Sandenburg'], 'coalitie' => [], 'gebeurtenissen' => 'Schoolstrijd, kiesrechtkwestie.', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Buitenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Utrecht)', 'ministersposten' => ['Minister van Buitenlandse Zaken'], 'foto' => ''],
        ['nummer' => 17, 'naam' => 'Joannes Kappeyne van de Coppello', 'volledige_naam' => 'Joannes Kappeyne van de Coppello', 'partij' => 'Liberaal', 'start' => '1877-11-03', 'eind' => '1879-08-20', 'huidig' => 0, 'geboren' => '1822-10-09', 'overleden' => '1895-07-28', 'geboorteplaats' => 'Den Haag', 'bio' => 'Liberaal kabinet dat een nieuwe Lageronderwijswet doorvoerde, wat de schoolstrijd verhevigde.', 'leeftijd' => 55, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Lageronderwijswet 1878'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Kappeyne van de Coppello'], 'coalitie' => [], 'gebeurtenissen' => 'Schoolstrijd.', 'speeches' => [], 'wetgeving' => ['Lageronderwijswet 1878'], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Binnenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Leiden)', 'ministersposten' => ['Minister van Binnenlandse Zaken'], 'foto' => ''],
        ['nummer' => 16, 'naam' => 'Jan Heemskerk Azn.', 'volledige_naam' => 'Jan Heemskerk Azn.', 'partij' => 'Conservatief', 'start' => '1874-08-27', 'eind' => '1877-11-03', 'huidig' => 0, 'geboren' => '1818-07-30', 'overleden' => '1897-10-09', 'geboorteplaats' => 'Amsterdam', 'bio' => 'Leidde zijn tweede, conservatieve kabinet.', 'leeftijd' => 56, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Heemskerk-Van Lynden van Sandenburg'], 'coalitie' => [], 'gebeurtenissen' => '', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Binnenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Athenaeum Illustre)', 'ministersposten' => ['Minister van Binnenlandse Zaken'], 'foto' => ''],
        ['nummer' => 15, 'naam' => 'Gerrit de Vries Azn.', 'volledige_naam' => 'Gerrit de Vries Azn.', 'partij' => 'Liberaal', 'start' => '1872-07-06', 'eind' => '1874-08-27', 'huidig' => 0, 'geboren' => '1818-02-22', 'overleden' => '1900-03-04', 'geboorteplaats' => 'Amsterdam', 'bio' => 'Volgde Thorbecke op na diens overlijden.', 'leeftijd' => 54, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['De Vries-Fransen van de Putte'], 'coalitie' => [], 'gebeurtenissen' => 'Overlijden van Thorbecke.', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Justitie', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => '', 'ministersposten' => ['Minister van Justitie'], 'foto' => ''],
        ['nummer' => 14, 'naam' => 'Johan Rudolph Thorbecke', 'volledige_naam' => 'Johan Rudolph Thorbecke', 'partij' => 'Liberaal', 'start' => '1871-01-04', 'eind' => '1872-06-04', 'huidig' => 0, 'geboren' => '1798-01-14', 'overleden' => '1872-06-04', 'geboorteplaats' => 'Zwolle', 'bio' => 'Grondlegger van de parlementaire democratie in Nederland. Dit was zijn derde en laatste kabinet. Hij overleed in ambt.', 'leeftijd' => 73, 'vroeg_leven' => '', 'carriere' => 'Hoogleraar, staatsman.', 'prestaties' => ['Grondlegger parlementaire democratie'], 'fun_facts' => [], 'echtgenoot' => 'Adelheid Solger', 'kinderen' => ['Johan', 'Willem', 'Rudolf', 'Marie', 'Herman', 'Henriette'], 'kabinetten' => ['Thorbecke I', 'Thorbecke II', 'Thorbecke III'], 'coalitie' => [], 'gebeurtenissen' => 'Overleed in ambt.', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Hoogleraar', 'waardering' => 'Wordt gezien als de belangrijkste staatsman van de 19e eeuw.', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Letteren en Rechten', 'ministersposten' => ['Minister van Binnenlandse Zaken'], 'foto' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Portrait_of_Johan_Rudolph_Thorbecke.jpg/256px-Portrait_of_Johan_Rudolph_Thorbecke.jpg'],
        ['nummer' => 13, 'naam' => 'Pieter Philip van Bosse', 'volledige_naam' => 'Pieter Philip van Bosse', 'partij' => 'Liberaal', 'start' => '1868-06-04', 'eind' => '1871-01-04', 'huidig' => 0, 'geboren' => '1809-12-16', 'overleden' => '1879-02-21', 'geboorteplaats' => 'Amsterdam', 'bio' => 'Liberaal kabinet dat zich richtte op financiën en infrastructuur.', 'leeftijd' => 58, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Afschaffing dagbladzegel'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Van Bosse-Fock'], 'coalitie' => [], 'gebeurtenissen' => '', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Financiën', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Athenaeum Illustre)', 'ministersposten' => ['Minister van Financiën'], 'foto' => ''],
        ['nummer' => 12, 'naam' => 'Julius van Zuylen van Nijevelt', 'volledige_naam' => 'Julius van Zuylen van Nijevelt', 'partij' => 'Conservatief', 'start' => '1866-06-01', 'eind' => '1868-06-04', 'huidig' => 0, 'geboren' => '1819-08-19', 'overleden' => '1894-07-01', 'geboorteplaats' => 'Luxemburg', 'bio' => 'Kabinet kwam ten val door de Luxemburgse kwestie, wat de vertrouwensregel in het parlement vestigde.', 'leeftijd' => 46, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Vestiging van de vertrouwensregel'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Van Zuylen van Nijevelt'], 'coalitie' => [], 'gebeurtenissen' => 'Luxemburgse kwestie.', 'speeches' => [], 'wetgeving' => [], 'crises' => ['Luxemburgse kwestie'], 'economie' => '', 'carriere_voor' => 'Minister van Buitenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Utrecht)', 'ministersposten' => ['Minister van Buitenlandse Zaken'], 'foto' => ''],
        ['nummer' => 11, 'naam' => 'Isaäc Fransen van de Putte', 'volledige_naam' => 'Isaäc Dignus Fransen van de Putte', 'partij' => 'Liberaal', 'start' => '1866-02-10', 'eind' => '1866-06-01', 'huidig' => 0, 'geboren' => '1822-03-22', 'overleden' => '1902-03-03', 'geboorteplaats' => 'Goes', 'bio' => 'Zeer kortstondig kabinet dat viel over de koloniale politiek.', 'leeftijd' => 43, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Fransen van de Putte'], 'coalitie' => [], 'gebeurtenissen' => 'Struikelde over het cultuurstelsel.', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Koloniën', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => '', 'ministersposten' => ['Minister van Koloniën'], 'foto' => ''],
        ['nummer' => 10, 'naam' => 'Johan Rudolph Thorbecke', 'volledige_naam' => 'Johan Rudolph Thorbecke', 'partij' => 'Liberaal', 'start' => '1862-01-31', 'eind' => '1866-02-10', 'huidig' => 0, 'geboren' => '1798-01-14', 'overleden' => '1872-06-04', 'geboorteplaats' => 'Zwolle', 'bio' => 'Zijn tweede kabinet voerde belangrijke wetgeving door, zoals de Wet op het Middelbaar Onderwijs.', 'leeftijd' => 64, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Wet op het Middelbaar Onderwijs (1863)'], 'fun_facts' => [], 'echtgenoot' => 'Adelheid Solger', 'kinderen' => [], 'kabinetten' => ['Thorbecke II'], 'coalitie' => [], 'gebeurtenissen' => '', 'speeches' => [], 'wetgeving' => ['Wet op het Middelbaar Onderwijs'], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Binnenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Letteren en Rechten', 'ministersposten' => ['Minister van Binnenlandse Zaken'], 'foto' => ''],
        ['nummer' => 9, 'naam' => 'Schelto van Heemstra', 'volledige_naam' => 'Schelto van Heemstra', 'partij' => 'Liberaal', 'start' => '1861-03-14', 'eind' => '1862-01-31', 'huidig' => 0, 'geboren' => '1807-11-14', 'overleden' => '1864-12-20', 'geboorteplaats' => 'Groningen', 'bio' => 'Liberaal overgangskabinet.', 'leeftijd' => 53, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Van Heemstra-Van Zuylen van Nijevelt'], 'coalitie' => [], 'gebeurtenissen' => '', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Binnenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Groningen)', 'ministersposten' => ['Minister van Binnenlandse Zaken'], 'foto' => ''],
        ['nummer' => 8, 'naam' => 'Floris Adriaan van Hall', 'volledige_naam' => 'Floris Adriaan van Hall', 'partij' => 'Conservatief-liberaal', 'start' => '1860-02-23', 'eind' => '1861-03-14', 'huidig' => 0, 'geboren' => '1791-05-15', 'overleden' => '1866-12-29', 'geboorteplaats' => 'Amsterdam', 'bio' => 'Leidde zijn derde kabinet.', 'leeftijd' => 68, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Van Hall-Van Heemstra'], 'coalitie' => [], 'gebeurtenissen' => '', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Buitenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Universiteit van Amsterdam, Leiden)', 'ministersposten' => ['Minister van Buitenlandse Zaken', 'Voorzitter van de Ministerraad (1853-1856)'], 'foto' => ''],
        ['nummer' => 7, 'naam' => 'Justinus van der Brugghen', 'volledige_naam' => 'Justinus van der Brugghen', 'partij' => 'Antirevolutionair', 'start' => '1856-07-01', 'eind' => '1858-03-18', 'huidig' => 0, 'geboren' => '1804-08-06', 'overleden' => '1863-10-02', 'geboorteplaats' => 'Nijmegen', 'bio' => 'Leider van een "ethisch-irenisch" kabinet dat een nieuwe onderwijswet tot stand bracht.', 'leeftijd' => 51, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Lageronderwijswet 1857'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Van der Brugghen'], 'coalitie' => [], 'gebeurtenissen' => 'Schoolstrijd.', 'speeches' => [], 'wetgeving' => ['Lageronderwijswet 1857'], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Justitie', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Leiden)', 'ministersposten' => ['Minister van Justitie'], 'foto' => ''],
        ['nummer' => 6, 'naam' => 'Floris Adriaan van Hall', 'volledige_naam' => 'Floris Adriaan van Hall', 'partij' => 'Conservatief-liberaal', 'start' => '1853-04-19', 'eind' => '1856-07-01', 'huidig' => 0, 'geboren' => '1791-05-15', 'overleden' => '1866-12-29', 'geboorteplaats' => 'Amsterdam', 'bio' => 'Leidde een conservatief kabinet na de Aprilbeweging.', 'leeftijd' => 61, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => [], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Van Hall-Donker Curtius'], 'coalitie' => [], 'gebeurtenissen' => 'Aprilbeweging (protest tegen herstel bisschoppelijke hiërarchie).', 'speeches' => [], 'wetgeving' => [], 'crises' => ['Aprilbeweging'], 'economie' => '', 'carriere_voor' => 'Minister van Buitenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Universiteit van Amsterdam, Leiden)', 'ministersposten' => ['Minister van Buitenlandse Zaken'], 'foto' => ''],
        ['nummer' => 5, 'naam' => 'Johan Rudolph Thorbecke', 'volledige_naam' => 'Johan Rudolph Thorbecke', 'partij' => 'Liberaal', 'start' => '1849-11-01', 'eind' => '1853-04-19', 'huidig' => 0, 'geboren' => '1798-01-14', 'overleden' => '1872-06-04', 'geboorteplaats' => 'Zwolle', 'bio' => 'Het eerste kabinet-Thorbecke dat de nieuwe grondwet implementeerde met wetten als de Provinciale Wet en Gemeentewet.', 'leeftijd' => 51, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Provinciale Wet', 'Gemeentewet', 'Kieswet'], 'fun_facts' => [], 'echtgenoot' => 'Adelheid Solger', 'kinderen' => [], 'kabinetten' => ['Thorbecke I'], 'coalitie' => [], 'gebeurtenissen' => 'Implementatie van de Grondwet van 1848.', 'speeches' => [], 'wetgeving' => ['Gemeentewet', 'Provinciale Wet'], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Binnenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Letteren en Rechten', 'ministersposten' => ['Minister van Binnenlandse Zaken'], 'foto' => ''],
        ['nummer' => 4, 'naam' => 'Jacob de Kempenaer', 'volledige_naam' => 'Jacobus Mattheüs de Kempenaer', 'partij' => 'Conservatief-liberaal', 'start' => '1848-11-21', 'eind' => '1849-11-01', 'huidig' => 0, 'geboren' => '1793-07-06', 'overleden' => '1870-02-12', 'geboorteplaats' => 'Amsterdam', 'bio' => 'Leidde een overgangskabinet dat de eerste directe verkiezingen voor de Tweede Kamer organiseerde.', 'leeftijd' => 55, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Organisatie eerste directe verkiezingen'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['De Kempenaer-Donker Curtius'], 'coalitie' => [], 'gebeurtenissen' => 'Eerste verkiezingen onder de nieuwe grondwet.', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Binnenlandse Zaken', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Leiden)', 'ministersposten' => ['Minister van Binnenlandse Zaken'], 'foto' => ''],
        ['nummer' => 3, 'naam' => 'Dirk Donker Curtius', 'volledige_naam' => 'Dirk Donker Curtius', 'partij' => 'Liberaal', 'start' => '1848-05-17', 'eind' => '1848-11-21', 'huidig' => 0, 'geboren' => '1792-10-19', 'overleden' => '1864-07-17', 'geboorteplaats' => 'Rotterdam', 'bio' => 'Leidde het kabinet dat de grondwetsherziening van Thorbecke afrondde.', 'leeftijd' => 55, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Afronding Grondwetsherziening 1848'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Donker Curtius-De Kempenaer'], 'coalitie' => [], 'gebeurtenissen' => 'Goedkeuring van de nieuwe Grondwet.', 'speeches' => [], 'wetgeving' => ['Grondwetsherziening 1848'], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Justitie', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => 'Rechten (Rijksuniversiteit Leiden)', 'ministersposten' => ['Minister van Justitie'], 'foto' => ''],
        ['nummer' => 2, 'naam' => 'Gerrit Schimmelpenninck', 'volledige_naam' => 'Gerrit graaf Schimmelpenninck', 'partij' => 'Conservatief-liberaal', 'start' => '1848-03-25', 'eind' => '1848-05-17', 'huidig' => 0, 'geboren' => '1794-02-25', 'overleden' => '1863-10-04', 'geboorteplaats' => 'Amsterdam', 'bio' => 'Eerste voorzitter van de ministerraad. Had de opdracht een grondwetsherziening voor te bereiden.', 'leeftijd' => 54, 'vroeg_leven' => '', 'carriere' => '', 'prestaties' => ['Voorzitter van de Grondwetscommissie'], 'fun_facts' => [], 'echtgenoot' => '', 'kinderen' => [], 'kabinetten' => ['Schimmelpenninck'], 'coalitie' => [], 'gebeurtenissen' => 'Revolutiejaar 1848, angst voor omwenteling.', 'speeches' => [], 'wetgeving' => [], 'crises' => [], 'economie' => '', 'carriere_voor' => 'Minister van Buitenlandse Zaken en Financiën', 'waardering' => '', 'controverses' => '', 'citaten' => [], 'onderwijs' => '', 'ministersposten' => ['Minister van Buitenlandse Zaken', 'Minister van Financiën'], 'foto' => '']
    ];

    $insertMPQuery = "
        INSERT IGNORE INTO nederlandse_ministers_presidenten
        (minister_president_nummer, naam, volledige_naam, partij, periode_start, periode_eind, is_huidig, geboren, overleden, geboorteplaats, biografie, leeftijd_bij_aantreden, vroeg_leven, politieke_carriere, prestaties, fun_facts, echtgenoot_echtgenote, kinderen, kabinetten, coalitiepartners, belangrijkste_gebeurtenissen, bekende_speeches, wetgeving, crises, economische_situatie, carrierre_voor_mp, historische_waardering, controverses, citaten, onderwijs, ministersposten_voor_mp, foto_url)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ";
    $stmt = $pdo->prepare($insertMPQuery);

    // Loop door de data en voer in, met json_encode voor de array-velden
    foreach ($ministers_presidenten as $mp) {
        $stmt->execute([
            $mp['nummer'], $mp['naam'], $mp['volledige_naam'], $mp['partij'], $mp['start'], $mp['eind'], $mp['huidig'],
            $mp['geboren'], $mp['overleden'], $mp['geboorteplaats'], $mp['bio'], $mp['leeftijd'], $mp['vroeg_leven'],
            $mp['carriere'], json_encode($mp['prestaties'], JSON_UNESCAPED_UNICODE), json_encode($mp['fun_facts'], JSON_UNESCAPED_UNICODE), $mp['echtgenoot'],
            json_encode($mp['kinderen'], JSON_UNESCAPED_UNICODE), json_encode($mp['kabinetten'], JSON_UNESCAPED_UNICODE), json_encode($mp['coalitie'], JSON_UNESCAPED_UNICODE),
            $mp['gebeurtenissen'], json_encode($mp['speeches'], JSON_UNESCAPED_UNICODE), json_encode($mp['wetgeving'], JSON_UNESCAPED_UNICODE), json_encode($mp['crises'], JSON_UNESCAPED_UNICODE),
            $mp['economie'], $mp['carriere_voor'], $mp['waardering'], $mp['controverses'], json_encode($mp['citaten'], JSON_UNESCAPED_UNICODE),
            $mp['onderwijs'], json_encode($mp['ministersposten'], JSON_UNESCAPED_UNICODE), $mp['foto']
        ]);
    }

    echo "✓ Alle ministers-presidenten (1848-heden) toegevoegd\n";

    // --- DATA VERKIEZINGEN ---
    $insertVerkiezingenQuery = "
        INSERT IGNORE INTO nederlandse_verkiezingen
        (jaar, partij_uitslagen, coalitie_partijen, coalitie_zetels, coalitie_type, oppositie_partijen, minister_president, minister_president_partij, kabinet_naam, kabinet_type, totaal_stemmen, opkomst_percentage, verkiezingsdata, kabinet_start_datum, formatie_duur_dagen, verkiezings_aanleiding, belangrijkste_themas, belangrijke_gebeurtenissen, opvallende_feiten, beschrijving, aantal_partijen_tk, nieuwe_partijen, grootste_winnaar, grootste_winnaar_aantal, grootste_verliezer, grootste_verliezer_aantal)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ";
    $stmt2 = $pdo->prepare($insertVerkiezingenQuery);

$verkiezingen = [
    [2023, '[{"partij":"PVV","zetels":37,"stemmen":2410481,"percentage":23.5},{"partij":"GL-PvdA","zetels":25,"stemmen":1565085,"percentage":15.7},{"partij":"NSC","zetels":20,"stemmen":1273123,"percentage":12.9},{"partij":"D66","zetels":9,"stemmen":609467,"percentage":6.1},{"partij":"BBB","zetels":7,"stemmen":441642,"percentage":4.5}]', '["PVV", "VVD", "NSC", "BBB"]', 88, 'extraparlementair', '["GL-PvdA", "D66", "CDA", "SP", "PvdD", "ChristenUnie"]', 'Dick Schoof', 'Onafhankelijk', 'Schoof', 'rechts', 9987431, 77.8, '2023-11-22', '2024-07-02', 223, 'kabinetsval', '["Immigratie", "Asiel", "Woningcrisis", "Stikstof", "Koopkracht"]', 'De verkiezingen volgden op de val van Rutte IV over immigratie. Mark Rutte kondigde zijn aftreden aan als partijleider.', 'PVV werd voor het eerst de grootste partij. Langste formatieperiode sinds 2017.', 'Deze verkiezingen markeerden het einde van het tijdperk-Rutte na 13 jaar.', 15, '["NSC", "BBB"]', 'PVV', 20, 'D66', -15],
    [2021, '[{"partij":"VVD","zetels":34,"stemmen":2252305,"percentage":21.9},{"partij":"D66","zetels":24,"stemmen":1529913,"percentage":15.0},{"partij":"PVV","zetels":17,"stemmen":1104226,"percentage":10.8},{"partij":"CDA","zetels":15,"stemmen":925395,"percentage":9.0},{"partij":"SP","zetels":9,"stemmen":600010,"percentage":5.9}]', '["VVD", "D66", "CDA", "ChristenUnie"]', 78, 'meerderheid', '["PVV", "SP", "PvdA", "GL", "FVD"]', 'Mark Rutte', 'VVD', 'Rutte IV', 'centrum-rechts', 10235000, 78.7, '2021-03-17', '2022-01-10', 299, 'vervroegd', '["Corona", "Klimaat", "Toeslagenaffaire", "Europa", "Zorg"]', 'Verkiezingen na val kabinet door toeslagenaffaire. Langste formatie ooit.', 'Langste formatie in Nederlandse geschiedenis (299 dagen).', 'Deze verkiezingen vonden plaats tijdens de coronapandemie.', 16, '["Volt", "JA21", "BBB"]', 'D66', 5, 'GroenLinks', -6],
    [2017, '[{"partij":"VVD","zetels":33},{"partij":"PVV","zetels":20},{"partij":"CDA","zetels":19},{"partij":"D66","zetels":19},{"partij":"GL","zetels":14}]', '["VVD", "CDA", "D66", "ChristenUnie"]', 76, 'meerderheid', '["PVV", "GL", "SP", "PvdA", "PvdD"]', 'Mark Rutte', 'VVD', 'Rutte III', 'centrum-rechts', 10500000, 81.9, '2017-03-15', '2017-10-26', 225, 'regulier', '["Europa", "Immigratie", "Economie", "Klimaat"]', 'Brexit-effect en populisme in Europa. PvdA verloor dramatisch.', 'Hoogste opkomst sinds 1986 (81.9%).', 'Deze verkiezingen werden gezien als een test voor het populisme.', 13, '["FVD", "DENK"]', 'GroenLinks', 10, 'PvdA', -29],
    [2012, '[{"partij":"VVD","zetels":41},{"partij":"PvdA","zetels":38},{"partij":"PVV","zetels":15},{"partij":"SP","zetels":15},{"partij":"CDA","zetels":13}]', '["VVD", "PvdA"]', 79, 'meerderheid', '["PVV", "SP", "CDA", "D66", "ChristenUnie"]', 'Mark Rutte', 'VVD', 'Rutte II', 'paars', 9424235, 74.6, '2012-09-12', '2012-11-05', 54, 'kabinetsval', '["Eurocrisis", "Bezuinigingen", "Zorg", "Onderwijs"]', 'Val Rutte I over Europese bezuinigingen. Nederland midden in Eurocrisis.', 'Eerste paarse kabinet sinds Kok.', 'Deze verkiezingen volgden op de val van Rutte I.', 11, '["50PLUS"]', 'PvdA', 8, 'CDA', -8],
    [2010, '[{"partij":"VVD","zetels":31},{"partij":"PvdA","zetels":30},{"partij":"PVV","zetels":24},{"partij":"CDA","zetels":21},{"partij":"SP","zetels":15}]', '["VVD", "CDA"]', 52, 'minderheid', '["PvdA", "SP", "D66", "GL", "ChristenUnie"]', 'Mark Rutte', 'VVD', 'Rutte I', 'centrum-rechts', 9415582, 75.4, '2010-06-09', '2010-10-14', 127, 'kabinetsval', '["Economische crisis", "Immigratie", "Europa", "Bezuinigingen"]', 'Val Balkenende IV tijdens financiële crisis. VVD werd nipt grootste.', 'Mark Rutte werd jongste minister-president ooit (43 jaar).', 'Deze verkiezingen markeerden het einde van het tijdperk-Balkenende.', 10, '[]', 'PVV', 15, 'CDA', -20],
    [2006, '[{"partij":"CDA","zetels":41},{"partij":"PvdA","zetels":33},{"partij":"SP","zetels":25},{"partij":"VVD","zetels":22},{"partij":"PVV","zetels":9}]', '["CDA", "PvdA", "ChristenUnie"]', 80, 'meerderheid', '["SP", "VVD", "PVV", "GroenLinks"]', 'Jan Peter Balkenende', 'CDA', 'Balkenende IV', 'centrum-links', 9315663, 80.4, '2006-11-22', '2007-02-22', 92, 'kabinetsval', '["Integratie", "Normen en waarden", "Economie", "Klimaat"]', 'Val van Balkenende III over de paspoortkwestie van Ayaan Hirsi Ali.', 'Historische overwinning voor de SP, die van 9 naar 25 zetels ging.', 'De PvdA leed een groot verlies ondanks de populariteit van lijsttrekker Wouter Bos.', 12, '["PVV"]', 'SP', 16, 'PvdA', -9],
    [2003, '[{"partij":"CDA","zetels":44},{"partij":"PvdA","zetels":42},{"partij":"VVD","zetels":28},{"partij":"SP","zetels":9},{"partij":"LPF","zetels":8}]', '["CDA", "VVD", "D66"]', 78, 'meerderheid', '["PvdA", "SP", "LPF", "GroenLinks"]', 'Jan Peter Balkenende', 'CDA', 'Balkenende II', 'centrum-rechts', 9654480, 80.0, '2003-01-22', '2003-05-27', 125, 'kabinetsval', '["Economische hervormingen", "Veiligheid", "Irak-oorlog"]', 'Verkiezingen na de snelle val van Balkenende I door interne ruzies bij de LPF.', 'De PvdA onder leiding van Wouter Bos maakte een spectaculaire comeback van 23 naar 42 zetels.', 'Het kabinet viel in 2006 na een conflict over het uitzetbeleid (zaak-Ayaan Hirsi Ali).', 10, '[]', 'PvdA', 19, 'LPF', -18],
    [2002, '[{"partij":"CDA","zetels":43},{"partij":"LPF","zetels":26},{"partij":"VVD","zetels":24},{"partij":"PvdA","zetels":23},{"partij":"GroenLinks","zetels":10}]', '["CDA", "LPF", "VVD"]', 93, 'meerderheid', '["PvdA", "GroenLinks", "SP", "D66"]', 'Jan Peter Balkenende', 'CDA', 'Balkenende I', 'centrum-rechts', 9502859, 79.1, '2002-05-15', '2002-07-22', 68, 'kabinetsval', '["Immigratie", "Veiligheid", "Zorg", "Publieke sector"]', 'Verkiezingen in de schaduw van de moord op Pim Fortuyn, 9 dagen voor de stembusgang.', 'De LPF kwam als nieuwe partij met 26 zetels de Kamer in, een unicum in de parlementaire geschiedenis.', 'Het kabinet viel al na 87 dagen door interne conflicten binnen de LPF-fractie.', 9, '["LPF"]', 'LPF', 26, 'PvdA', -22],
    [1998, '[{"partij":"PvdA","zetels":45},{"partij":"VVD","zetels":38},{"partij":"CDA","zetels":29},{"partij":"D66","zetels":14}]', '["PvdA", "VVD", "D66"]', 97, 'meerderheid', '["CDA", "GroenLinks", "SP"]', 'Wim Kok', 'PvdA', 'Kok II', 'paars', 9649549, 73.3, '1998-05-06', '1998-08-03', 89, 'Einde termijn', '["Economie", "Werkgelegenheid"]', 'Voortzetting van het succesvolle Paarse kabinet.', 'De "Paarse" coalitie zonder confessionele partijen werd voortgezet.', 'Verkiezingen in een tijd van grote economische voorspoed.', 10, '[]', 'GroenLinks', 6, 'CDA', -5],
    [1994, '[{"partij":"PvdA","zetels":37},{"partij":"CDA","zetels":34},{"partij":"VVD","zetels":31},{"partij":"D66","zetels":24}]', '["PvdA", "VVD", "D66"]', 92, 'meerderheid', '["CDA", "SP", "GroenLinks"]', 'Wim Kok', 'PvdA', 'Kok I', 'paars', 9380999, 78.8, '1994-05-03', '1994-08-22', 111, 'Einde termijn', '["Economie", "Sociale zekerheid"]', 'Historische verkiezingsnederlaag voor het CDA. Eerste kabinet sinds 1918 zonder confessionele partijen.', 'De formatie van het "Paarse" kabinet was een politieke aardverschuiving.', 'Markeerde het begin van de Paarse kabinetten.', 9, '[]', 'D66', 12, 'CDA', -20],
    [1989, '[{"partij":"CDA","zetels":54},{"partij":"PvdA","zetels":49},{"partij":"VVD","zetels":22},{"partij":"D66","zetels":12}]', '["CDA", "PvdA"]', 103, 'meerderheid', '["VVD", "D66", "GroenLinks"]', 'Ruud Lubbers', 'CDA', 'Lubbers III', 'centrum-links', 8933970, 80.3, '1989-09-06', '1989-11-07', 62, 'kabinetsval', '["Milieu", "Reiskostenforfait", "Economie"]', 'Val van Lubbers II over het reiskostenforfait. PvdA keerde terug in de regering.', 'Eerste verkiezingen waaraan GroenLinks (fusie van CPN, PSP, PPR en EVP) meedeed.', 'Dit kabinet zat de volledige termijn uit en voerde o.a. de Wet op de studiefinanciering in.', 10, '["GroenLinks"]', 'D66', 3, 'VVD', -5],
    [1986, '[{"partij":"CDA","zetels":54},{"partij":"PvdA","zetels":52},{"partij":"VVD","zetels":27}]', '["CDA", "VVD"]', 81, 'meerderheid', '["PvdA", "D66", "SP"]', 'Ruud Lubbers', 'CDA', 'Lubbers II', 'centrum-rechts', 9177547, 85.8, '1986-05-21', '1986-07-14', 54, 'Einde termijn', '["Kernenergie (Tsjernobyl)", "Bezuinigingen", "Werkloosheid"]', 'PvdA won fors onder nieuwe leider Wim Kok, maar de zittende coalitie behield haar meerderheid.', 'De kernramp van Tsjernobyl vond vlak voor de verkiezingen plaats en was een groot thema.', '"Laat Lubbers z\'n karwei afmaken" was de winnende slogan van het CDA.', 7, '[]', 'PvdA', 5, 'CPN', -3],
    [1982, '[{"partij":"PvdA","zetels":47},{"partij":"CDA","zetels":45},{"partij":"VVD","zetels":36},{"partij":"D66","zetels":6}]', '["CDA", "VVD"]', 81, 'meerderheid', '["PvdA", "D66", "SP", "CPN"]', 'Ruud Lubbers', 'CDA', 'Lubbers I', 'centrum-rechts', 8243621, 81.0, '1982-09-08', '1982-11-04', 57, 'kabinetsval', '["Economische crisis", "Bezuinigingen", "Werkloosheid"]', 'Na de snelle val van het tweede kabinet Van Agt (CDA, PvdA, D66).', 'Het Akkoord van Wassenaar, de basis voor het poldermodel, werd onder dit kabinet gesloten.', 'Het kabinet voerde forse bezuinigingen door om de economische crisis te bestrijden.', 13, '["Centrumpartij"]', 'VVD', 10, 'D66', -11],
    [1977, '[{"partij":"PvdA","zetels":53},{"partij":"CDA","zetels":49},{"partij":"VVD","zetels":28},{"partij":"D66","zetels":8}]', '["CDA", "VVD"]', 77, 'meerderheid', '["PvdA", "D66", "SGP"]', 'Dries van Agt', 'CDA', 'Van Agt I', 'centrum-rechts', 8829777, 88.0, '1977-05-25', '1977-12-19', 208, 'Einde termijn', '["Economie", "Abortus", "Zuid-Molukkers"]', 'De PvdA van Joop den Uyl behaalde een historische overwinning, maar belandde toch in de oppositie.', 'De formatie duurde een recordtijd (208 dagen) en leidde tot het "verraad" van de PvdA.', 'Deze verkiezingen volgden op de roerige periode van het kabinet-Den Uyl.', 11, '[]', 'PvdA', 10, 'KVP/ARP/CHU (naar CDA)', -1],
    [1972, '[{"partij":"PvdA","zetels":43},{"partij":"KVP","zetels":27},{"partij":"VVD","zetels":22},{"partij":"ARP","zetels":14}]', '["PvdA", "KVP", "ARP", "D66", "PPR"]', 97, 'meerderheid', '["VVD", "CHU", "DS\'70"]', 'Joop den Uyl', 'PvdA', 'Den Uyl', 'centrum-links', 7349191, 83.5, '1972-11-29', '1973-05-11', 163, 'kabinetsval', '["Economie", "Spreiding van kennis, macht en inkomen", "Oliecrisis"]', 'De verkiezingen werden veroorzaakt door de val van het kabinet-Biesheuvel I.', 'Het kabinet-Den Uyl was een van de meest progressieve en polariserende kabinetten uit de geschiedenis.', 'De oliecrisis van 1973 en de autoloze zondagen zijn onlosmakelijk met dit kabinet verbonden.', 14, '[]', 'PvdA', 4, 'DS\'70', -6],
    [1967, '[{"partij":"KVP","zetels":42},{"partij":"PvdA","zetels":37},{"partij":"VVD","zetels":17},{"partij":"ARP","zetels":15}]', '["KVP", "VVD", "ARP", "CHU"]', 83, 'meerderheid', '["PvdA", "D66", "CPN"]', 'Piet de Jong', 'KVP', 'De Jong', 'centrum-rechts', 6848079, 94.9, '1967-02-15', '1967-04-05', 49, 'kabinetsval', '["Economie", "Democratisering", "Vietnamoorlog"]', 'De opkomst van de nieuwe partij D\'66 die met 7 zetels in de Kamer kwam.', 'Het kabinet-De Jong was het eerste naoorlogse kabinet dat de rit uitzat.', 'Deze periode kenmerkte zich door maatschappelijke onrust en de roep om democratisering (Maagdenhuisbezetting).', 11, '["D66"]', 'D66', 7, 'PvdA', -6],
    [1959, '[{"partij":"KVP","zetels":49},{"partij":"PvdA","zetels":48},{"partij":"VVD","zetels":19},{"partij":"ARP","zetels":14}]', '["KVP", "VVD", "ARP", "CHU"]', 94, 'meerderheid', '["PvdA", "CPN", "SGP"]', 'Jan de Quay', 'KVP', 'De Quay', 'centrum-rechts', 6173009, 95.5, '1959-03-12', '1959-05-19', 68, 'kabinetsval', '["Wederopbouw", "Vrije zaterdag", "Nieuw-Guinea"]', 'Eerste verkiezingen na de val van het vierde kabinet-Drees en het einde van de rooms-rode coalities.', 'Het kabinet-De Quay introduceerde de vrije zaterdag en de televisie-uitzendingen werden uitgebreid.', 'De VVD werd de derde partij van het land en nam weer deel aan de regering.', 12, '[]', 'VVD', 6, 'PvdA', -2],
    [1946, '[{"partij":"KVP","zetels":32},{"partij":"PvdA","zetels":29},{"partij":"ARP","zetels":13},{"partij":"CHU","zetels":8},{"partij":"CPN","zetels":10}]', '["KVP", "PvdA"]', 61, 'meerderheid', '["ARP", "CHU", "CPN"]', 'Louis Beel', 'KVP', 'Beel I', 'rooms-rood', 4764036, 93.1, '1946-05-17', '1946-07-03', 47, 'Eerste naoorlogse verkiezingen', '["Wederopbouw", "Indonesië"]', 'Eerste verkiezingen na WOII. KVP werd de grootste partij.', 'De "Rooms-Rode" samenwerking domineerde de naoorlogse politiek.', 'Hoge opkomst, land moest opnieuw worden opgebouwd.', 10, '["PvdA"]', 'KVP', 15, 'VDB', -6],
    [1918, '[{"partij":"RKSP","zetels":30},{"partij":"SDAP","zetels":22},{"partij":"ARP","zetels":13}]', '["RKSP", "ARP", "CHU"]', 50, 'meerderheid', '["SDAP", "VDB"]', 'Charles Ruijs de Beerenbrouck', 'RKSP', 'Ruijs de Beerenbrouck I', 'confessioneel', 1334693, 33.6, '1918-07-03', '1918-09-09', 68, 'Grondwetsherziening 1917', '["Sociale kwestie", "Wederopbouw na WOI"]', 'Eerste verkiezingen met algemeen mannenkiesrecht en evenredige vertegenwoordiging.', 'Lage opkomst omdat het systeem nieuw was en vrouwen nog niet mochten stemmen.', 'De confessionele partijen behaalden een absolute meerderheid.', 20, '[]', 'SDAP', 7, 'Liberalen', -20],
    [1888, '[{"partij":"Katholieken", "zetels":25}, {"partij":"ARP", "zetels":27}, {"partij":"Liberalen", "zetels":46}]', '["Katholieken", "ARP"]', 52, 'meerderheid', '["Liberalen"]', 'Aeneas Mackay', 'ARP', 'Mackay', 'confessioneel', 309000, 68.9, '1888-03-06', '1888-04-21', 46, 'Grondwetsherziening 1887', '["Schoolstrijd"]', 'Eerste verkiezingen na grondwetsherziening die kiesrecht uitbreidde. Confessionelen (rechts) wonnen voor het eerst.', 'Eerste rechtse (confessionele) coalitie kwam aan de macht.', 'De schoolstrijd was het allesoverheersende thema.', 3, '[]', 'Confessionelen', 20, 'Liberalen', -20],
    [1848, '[{"partij": "Liberalen", "zetels": 40}, {"partij": "Conservatieven", "zetels": 15}, {"partij": "Conservatief-liberaal", "zetels": 13}]', '["Liberalen (Thorbeckianen)"]', 40, 'meerderheid', '["Conservatieven"]', 'Jacob de Kempenaer', 'Conservatief-liberaal', 'De Kempenaer-Donker Curtius', 'liberaal', 23000, 27.5, '1848-11-30', '1849-11-01', -9, 'Grondwetsherziening 1848', '["Implementatie Grondwet"]', 'Eerste directe verkiezingen voor de Tweede Kamer, na de Grondwetsherziening van Thorbecke.', 'Alleen mannen die een bepaald bedrag aan belasting betaalden mochten stemmen (censuskiesrecht). Opkomst was hierdoor laag.', 'De liberalen, voorstanders van de nieuwe grondwet, wonnen een meerderheid.', 3, '[]', 'Liberalen', 40, 'Conservatieven', 0]
];

    foreach ($verkiezingen as $verkiezing) {
        $stmt2->execute($verkiezing);
    }
    
    echo "✓ Alle verkiezingsgegevens toegevoegd\n";


    echo "\n=== Migratie Succesvol Voltooid ===\n";
    echo "Nederlandse verkiezingen pagina is nu beschikbaar op: " . (defined('URLROOT') ? URLROOT : '[URLROOT]') . "/nederlandse-verkiezingen\n";

} catch (PDOException $e) {
    echo "Database fout: " . $e->getMessage() . "\n";
    exit(1);
} catch (Exception $e) {
    echo "Algemene fout: " . $e->getMessage() . "\n";
    exit(1);
}
?>